// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetBookData() {
  return window['go']['main']['App']['GetBookData']();
}

export function GetMarkdownContent(arg1) {
  return window['go']['main']['App']['GetMarkdownContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
