// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {main} from '../models';

export function ClipboardGetText(arg1:context.Context):Promise<string>;

export function ClipboardSetText(arg1:context.Context):Promise<string>;

export function GetBookData():Promise<main.BookData>;

export function GetMarkdownContent(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function WindowReload(arg1:context.Context):Promise<void>;

export function WindowReloadApp(arg1:context.Context):Promise<void>;

export function WindowSetAlwaysOnTop(arg1:context.Context):Promise<void>;
