// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClipboardGetText(arg1) {
  return window['go']['main']['App']['ClipboardGetText'](arg1);
}

export function ClipboardSetText(arg1) {
  return window['go']['main']['App']['ClipboardSetText'](arg1);
}

export function GetBookData() {
  return window['go']['main']['App']['GetBookData']();
}

export function GetMarkdownContent(arg1) {
  return window['go']['main']['App']['GetMarkdownContent'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function WindowReload(arg1) {
  return window['go']['main']['App']['WindowReload'](arg1);
}

export function WindowReloadApp(arg1) {
  return window['go']['main']['App']['WindowReloadApp'](arg1);
}

export function WindowSetAlwaysOnTop(arg1) {
  return window['go']['main']['App']['WindowSetAlwaysOnTop'](arg1);
}
